
// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6FUOzUHzE6RrI_tc7PAtj9gF7709A_Y',
    appId: '1:1048662921037:web:c9c8c2a955a53b8cecf104',
    messagingSenderId: '1048662921037',
    projectId: 'sf333-mobileappdev-project',
    authDomain: 'sf333-mobileappdev-project.firebaseapp.com',
    storageBucket: 'sf333-mobileappdev-project.firebasestorage.app',
    measurementId: 'G-SWH7VPXN20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_bLnYgcLvPOJ2j0BmCorVSZ1ShWWahA',
    appId: '1:1048662921037:android:0bd41579975b002fecf104',
    messagingSenderId: '1048662921037',
    projectId: 'sf333-mobileappdev-project',
    storageBucket: 'sf333-mobileappdev-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFg_DGRB7zFgvoWGJj4SQHkyZnfd80iM',
    appId: '1:1048662921037:ios:688ea1d319f25fd9ecf104',
    messagingSenderId: '1048662921037',
    projectId: 'sf333-mobileappdev-project',
    storageBucket: 'sf333-mobileappdev-project.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFg_DGRB7zFgvoWGJj4SQHkyZnfd80iM',
    appId: '1:1048662921037:ios:688ea1d319f25fd9ecf104',
    messagingSenderId: '1048662921037',
    projectId: 'sf333-mobileappdev-project',
    storageBucket: 'sf333-mobileappdev-project.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf6FUOzUHzE6RrI_tc7PAtj9gF7709A_Y',
    appId: '1:1048662921037:web:063118b59f42b371ecf104',
    messagingSenderId: '1048662921037',
    projectId: 'sf333-mobileappdev-project',
    authDomain: 'sf333-mobileappdev-project.firebaseapp.com',
    storageBucket: 'sf333-mobileappdev-project.firebasestorage.app',
    measurementId: 'G-85M7NF2304',
  );
}
